# Generated by Django 5.0.6 on 2024-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
