# Generated by Django 5.0.6 on 2024-06-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_remove_contact_id_alter_contact_sno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserLogins',
        ),
    ]
